In [1]:
##Importing pyodbc module
import pandas as  pd
import pyodbc as odbc
import numpy as np

##connecting to your database through ODBC
cnxn = odbc.connect('DSN=249-serv;UID=support;PWD=support', autocommit=True)
cursor = cnxn.cursor()

##connecting to your database through ODBC
c250 = odbc.connect('DSN=250-serv;UID=sa;PWD=pass1234', autocommit=True)
cursor = c250.cursor()

##connecting to your database through ODBC
cnxn196 = odbc.connect('DSN=196-serv;UID=support;PWD=support', autocommit=True)
cursor196 = cnxn196.cursor()

cnxn195 = odbc.connect('DSN=195-serv;UID=support;PWD=support', autocommit=True)
cursor195 = cnxn195.cursor()

OperationalError: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53)')

In [ ]:
t = '60 [tgljam],[noip],[noseq],[cntpr],[cntprset],[cntprall],[cntprsetall]'
te = 60

dum = 0

check1911 = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35._' "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check1911

check1911C = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.199' and noseq = 11 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check1911C

check9720 = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.97' and noseq = 20 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check9720

check9721 = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.97' and noseq = 21 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check9721

check9810 = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.98' and noseq = 10 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check9810

check9826 = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.98' and noseq = 26 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check9826

check999 = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.99' and noseq = 9 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check999

check9910 = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.99' and noseq = 10 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check9910






###
dum971 = dum9718= dum9719= dum9720= dum9721= dum981= dum982= dum989= dum9810= 0
dum9821= dum9822= dum9823= dum9824= dum9825= dum9826= dum9827= dum9828= 0
dum995= dum996= dum997= dum998= dum999= dum9910= dum9911= dum9912= 0
i = 0
for i in range (te):
    if i < (te-1):
        
        cal9718 = check1911.cntpr[i] + check1911.cntprall [i+1] - check1911.cntprall [i]
        total9718 = cal9718 + dum9718
        dum9718 = total9718
        
        cal9719 = check1911C.cntpr[i] + check1911C.cntprall [i+1] - check1911C.cntprall [i]
        total9719 = cal9719 + dum9719
        dum9719 = total9719
        
        cal9720 = check9720.cntpr[i] + check9720.cntprall [i+1] - check9720.cntprall [i]
        total9720 = cal9720 + dum9720
        dum9720 = total9720
        scheck9720 = check9720.cntpr.loc[0:60].sum()
        
        cal9721 = check9721.cntpr[i] + check9721.cntprall [i+1] - check9721.cntprall [i]
        total9721 = cal9721 + dum9721
        dum9721 = total9721
        scheck9721 = check9721.cntpr.loc[0:60].sum()
        
        cal9810 = check9810.cntpr[i] + check9810.cntprall [i+1] - check9810.cntprall [i]
        total9810 = cal9810 + dum9810
        dum9810 = total9810
        scheck9810 = check9810.cntpr.loc[0:60].sum()
        
        cal9826 = check9826.cntpr[i] + check9826.cntprall [i+1] - check9826.cntprall [i]
        total9826 = cal9826 + dum9826
        dum9826 = total9826
        scheck9826 = check9826.cntpr.loc[0:60].sum()
        
        cal999 = check999.cntpr[i] + check999.cntprall [i+1] - check999.cntprall [i]
        total999 = cal999 + dum999
        dum999 = total999
        scheck999 = check999.cntpr.loc[0:60].sum()
        
        cal9910 = check9910.cntpr[i] + check9910.cntprall [i+1] - check9910.cntprall [i]
        total9910 = cal9910 + dum9910
        dum9910 = total9910
        scheck9910 = check9910.cntpr.loc[0:60].sum()
        
        

d = {'Area': [  'pwd3-serv', 'cream-serv','9720', '9721','9810', '9826','999', '9910'], 
     'Diff': [total9718    , total9719   ,total9720, total9721,total9810, total9826,total999, total9910 ]}
df = pd.DataFrame(data=d)
df

In [ ]:
flaw = check1911

bad_list = []
for i in range (te):
    if i < (te-1):
        calcu = flaw.cntpr[i] + flaw.cntprall [i+1] - flaw.cntprall [i]
        bad_list.append (calcu)        
        blist_frame = pd.DataFrame(data=bad_list)
flaw['different'] = blist_frame
show_result = flaw[((flaw['different'])<0) | ((flaw['different'])>0)]
show_result

In [ ]:
check1911C = pd.read_sql("Select top "+t+" from count_bs "
                    "where noip = '172.20.35.97' and noseq = 21 "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn195 )
check1911C