In [1]:
##Importing pyodbc module
import pandas as  pd
import pyodbc as odbc
import numpy as np

In [2]:
##connecting to your database through ODBC
cnxn = odbc.connect('DSN=250-serv;UID=sa;PWD=pass1234', autocommit=True)
cursor = cnxn.cursor()

OperationalError: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53)')

In [ ]:
n7c1 = pd.read_sql("Select top 480 * from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '18' "
                     #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7c1['val_before']= n7c1 ['cntprall'] - n7c1 ['cntpr']

n7c2 = pd.read_sql("Select top 480 * from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '19' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7c2['val_before']= n7c2 ['cntprall'] - n7c2 ['cntpr']

n7d1 = pd.read_sql("Select top 480 * from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '20' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7d1['val_before']= n7d1 ['cntprall'] - n7d1 ['cntpr']

n7d2 = pd.read_sql("Select top 30 * from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '21' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7d2['val_before']= n7d2 ['cntprall'] - n7d2 ['cntpr']

n7e1 = pd.read_sql("Select top 480 * from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '1' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7e1['val_before']= n7e1 ['cntprall'] - n7e1 ['cntpr']

n7e2 = pd.read_sql("Select top 480 * from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '9' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7e2['val_before']= n7e2 ['cntprall'] - n7e2 ['cntpr']

n7f1 = pd.read_sql("Select top 480 * from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '2' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7f1['val_before']= n7f1 ['cntprall'] - n7f1 ['cntpr']

n7f2 = pd.read_sql("Select top 480 * from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '10' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )

#n7f2['val_before']= n7f2 ['cntprall'] - n7f2 ['cntpr']

In [ ]:
n7c1.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7C1.xlsx', index = False)
n7c2.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7C2.xlsx', index = False)
n7d1.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7D1.xlsx', index = False)
n7d2.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7D2.xlsx', index = False)
n7e1.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7E1.xlsx', index = False)
n7e2.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7E2.xlsx', index = False)
n7f1.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7F1.xlsx', index = False)
n7f2.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7F2.xlsx', index = False)

In [ ]:
n7c2 = pd.read_sql("Select * from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '19' "
                     #"and tgljam between '2021-04-01 06:00:00.000' and '2021-04-01 11:30:00.000' "
                    "order by tgljam desc"
, cnxn )
#n7c2.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7C2.xlsx', index = False)

In [ ]:
n7d1 = pd.read_sql("Select * from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '11' "
                     "and tgljam between '2021-04-01 06:00:00.000' and '2021-04-01 11:30:00.000' "
                    "order by tgljam desc"
, cnxn )
#n7d1.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\BS_N7D1.xlsx', index = False)

In [ ]:
##connecting to your database through ODBC
cnxn196 = odbc.connect('DSN=196-serv;UID=support;PWD=support', autocommit=True)
cursor196 = cnxn196.cursor()

In [ ]:
n7c1x = pd.read_sql("Select top 60 [Tgljam],[NoIP],[NoSeq],[CntPr] from prod_counter "
                    "where noip = '172.20.35.97' and noseq = '18' "
                     #"and tgljam between '2021-04-01 06:00:00.000' and '2021-04-01 11:30:00.000' "
                    "order by tgljam desc"
, cnxn196 )

n7c1 = pd.read_sql("Select top 30 [tgljam],[noip],[noseq],[cntpr] from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '18' "
                     #"and tgljam between '2021-04-01 06:00:00.000' and '2021-04-01 11:30:00.000' "
                    "order by tgljam desc"
, cnxn )
n7c1['selisih'] = n7c1 ['cntpr'] - n7c1x ['CntPr']

In [ ]:
n7d2 = pd.read_sql("Select top 30 * from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '21' "
                      #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )
n7d2.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\n7d2__.xlsx', index = False)

In [ ]:
n8f1 = pd.read_sql("Select top 200 * from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '22' "
                     #"and tgljam between '2021-04-03 12:00:00.000' and '2021-04-03 20:30:00.000' "
                    "order by tgljam desc"
, cnxn )
n8f1

In [ ]:
x = '97'
y = '18'
s96 = pd.read_sql("Select top 30 [Tgljam],[NoIP],[NoSeq],[CntPr] from prod_counter "
                    "where noip = '172.20.35."+x+"'"" and noseq = '"+y+"'"
                     "and tgljam between '2021-04-09 06:00:00.000' and '2021-04-09 15:30:00.000' "
                    "order by tgljam desc"
, cnxn196 )

s25 = pd.read_sql("Select top 30 [tgljam],[noip],[noseq],[cntpr],[cntprall] from Count_BS "
                    "where noip = '172.20.35."+x+"'"" and noseq = '"+y+"'"
                     "and tgljam between '2021-04-09 12:00:00.000' and '2021-04-09 15:30:00.000' "
                    "order by tgljam desc"
, cnxn )
s96['cntprbs'] = s25 ['cntpr']
s96['gap_bs_cntr'] = s25 ['cntpr'] - s96 ['CntPr']
s96['cntprall'] = s25 ['cntprall']
s96['cntpr_before'] = s96['cntprall'] - s25 ['cntpr']
s96

In [ ]:
x = '97'
y = '18'

s25 = pd.read_sql("Select top 60 [tgljam],[noip],[noseq],[cntpr],[cntprset],[cntprall],[cntprsetall] from Count_BS "
                    "where noip = '172.20.35."+x+"'"" and noseq = '"+y+"'"
                     "and tgljam between '2021-04-12 05:00:00.000' and '2021-04-12 09:00:00.000' "
                    " order by tgljam desc"
, cnxn )

s25
#s25.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\n8h1_8apr.xlsx', index = False)

In [ ]:
t = '60 [tgljam],[noip],[noseq],[cntpr],[cntprset],[cntprall],[cntprsetall]'
te = 60
dum = 0

check9718 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '18' "
                     #"and tgljam >= '2021-04-29 09:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9718
check9718.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9718.xlsx', index = False)

check9719 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '19' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9719
check9719.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9719.xlsx', index = False)

check9720 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '20' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9720
check9720.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9720.xlsx', index = False)

check9721 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.97' and noseq = '21' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9721
check9721.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9721.xlsx', index = False)

check981 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '1' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check981
check981.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check981.xlsx', index = False)

check982 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '2' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check982
check982.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check982.xlsx', index = False)

check989 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '9' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check989
check989.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check989.xlsx', index = False)

check9810 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '10' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9810
check9810.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9810.xlsx', index = False)

##########################################################################################
check9821 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '21' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9821
check9821.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9821.xlsx', index = False)

check9822 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '22' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9822
check9822.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9822.xlsx', index = False)

check9823 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '23' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9823
check9823.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9823.xlsx', index = False)

check9824 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '24' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9824
check9824.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9824.xlsx', index = False)

check9825 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '25' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9825
check9825.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9825.xlsx', index = False)

check9826 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '26' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9826
check9826.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9826.xlsx', index = False)

check9827 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '27' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9827
check9827.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9827.xlsx', index = False)

check9828 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.98' and noseq = '28' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9828
check9828.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9828.xlsx', index = False)

check995 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '5' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check995
check995.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check995.xlsx', index = False)

check996 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '6' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check996
check996.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check996.xlsx', index = False)

check997 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '7' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check997
check997.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check997.xlsx', index = False)

check998 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '8' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check998
check998.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check998.xlsx', index = False)

check999 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '9' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check999
check999.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check999.xlsx', index = False)

check9910 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '10' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9910
check9910.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9910.xlsx', index = False)

check9911 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '11' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9911
check9911.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9911.xlsx', index = False)

check9912 = pd.read_sql("Select top "+t+" from Count_BS "
                    "where noip = '172.20.35.99' and noseq = '12' "
                     #"and tgljam between '2021-04-26 05:30:00.000' and '2021-04-26 06:30:00.000' "
                    "order by tgljam desc"
                   , cnxn )
check9912
check9912.to_excel(r'C:\Users\akaarinda\Documents\DataScience\DSC\trial Lab\check9912.xlsx', index = False)
###################################################################

i = 0 
dum9718= dum9719= dum9720= dum9721= dum981= dum982= dum989= dum9810= 0
dum9821= dum9822= dum9823= dum9824= dum9825= dum9826= dum9827= dum9828= 0
dum995= dum996= dum997= dum998= dum999= dum9910= dum9911= dum9912= 0

for i in range (te):
    if i < (te-1):
        
        cal9718 = check9718.cntpr[i] + check9718.cntprall [i+1] - check9718.cntprall [i]
        total9718 = cal9718 + dum9718
        dum9718 = total9718
        
        cal9719 = check9719.cntpr[i] + check9719.cntprall [i+1] - check9719.cntprall [i]
        total9719 = cal9719 + dum9719
        dum9719 = total9719
        
        cal9720 = check9720.cntpr[i] + check9720.cntprall [i+1] - check9720.cntprall [i]
        total9720 = cal9720 + dum9720
        dum9720 = total9720
        
        cal9721 = check9721.cntpr[i] + check9721.cntprall [i+1] - check9721.cntprall [i]
        total9721 = cal9721 + dum9721
        dum9721 = total9721
        
        cal981 = check981.cntpr[i] + check981.cntprall [i+1] - check981.cntprall [i]
        total981 = cal981 + dum981
        dum981 = total981
        
        cal982 = check982.cntpr[i] + check982.cntprall [i+1] - check982.cntprall [i]
        total982 = cal982 + dum982
        dum982 = total982
        
        cal989 = check989.cntpr[i] + check989.cntprall [i+1] - check989.cntprall [i]
        total989 = cal989 + dum989
        dum989 = total989
        
        cal9810 = check9810.cntpr[i] + check9810.cntprall [i+1] - check9810.cntprall [i]
        total9810 = cal9810 + dum9810
        dum9810 = total9810
        
        cal9821 = check9821.cntpr[i] + check9821.cntprall [i+1] - check9821.cntprall [i]
        total9821 = cal9821 + dum9821
        dum9821 = total9821
        
        cal9822 = check9822.cntpr[i] + check9822.cntprall [i+1] - check9822.cntprall [i]
        total9822 = cal9822 + dum9822
        dum9822 = total9822
        
        cal9823 = check9823.cntpr[i] + check9823.cntprall [i+1] - check9823.cntprall [i]
        total9823 = cal9823 + dum9823
        dum9823 = total9823
        
        cal9824 = check9824.cntpr[i] + check9824.cntprall [i+1] - check9824.cntprall [i]
        total9824 = cal9824 + dum9824
        dum9824 = total9824
        
 

        
        
d = {'Area': [  '9718', '9719', '9720', '9721', '981' , '982'  , '989'  , '9810',
                '9821', '9822', '9823', '9824', '9825', '9826' , '9827' , '9828',
               
             ], 
     'Diff': [total9718, total9719, total9720, total9721, total981 , total982, total989, total9810,
              total9821, total9822, total9823, total9824, total9718, total9718, total9718, total9718,
             ]}
df = pd.DataFrame(data=d)
df

In [ ]:
flaw = check9720

bad_list = []
for i in range (te):
    if i < (te-1):
        calcu = flaw.cntpr[i] + flaw.cntprall [i+1] - flaw.cntprall [i]
        bad_list.append (calcu)        
        blist_frame = pd.DataFrame(data=bad_list)
flaw['different'] = blist_frame
show_result = flaw[((flaw['different'])<0) | ((flaw['different'])>0)]
show_result

In [ ]:
flaw[86:93]